export const searchDatas = [
  'monster',
  'avengers',
  'sjanna of love',
  'water',
  'joy land',
  'shining',
  'spring of seoul',
  'your name is',
  'Intern',
  'eterners',
  'building',
  'vet',
  'hard job',
  'with god',
  'guardians of galaxy',
  'black',
  'spider man',
  'black widow',
  '',
];
